version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - bencodezen
  labels:
  - dependencies
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.23
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.12
    - 7.13.15
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: chokidar
    versions:
    - 3.5.0
  - dependency-name: prismjs
    versions:
    - 1.21.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
